#!/bin/bash

echo "=========================================="
echo "   FOOD ORDERING APP - FREE DEPLOYMENT"
echo "=========================================="
echo ""
echo "✅ All code is ready!"
echo ""
echo "📋 DEPLOYMENT STEPS:"
echo ""
echo "STEP 1: Create GitHub Account"
echo "   → Go to: https://github.com/signup"
echo "   → Sign up with email"
echo "   → Done!"
echo ""
echo "STEP 2: Deploy Backend (Railway)"
echo "   → Go to: https://railway.app"
echo "   → Click: Login with GitHub"
echo "   → Click: New Project"
echo "   → Click: Deploy from GitHub repo"
echo "   → Select: your repository"
echo "   → Done! Backend will be live in 5 minutes"
echo ""
echo "STEP 3: Deploy Frontend (Vercel)"
echo "   → Go to: https://vercel.com"
echo "   → Click: Continue with GitHub"
echo "   → Click: Add New Project"
echo "   → Import: your repository"
echo "   → Root Directory: frontend"
echo "   → Build Command: npx expo export -p web"
echo "   → Output Directory: dist"
echo "   → Environment Variable:"
echo "      Name: EXPO_PUBLIC_BACKEND_URL"
echo "      Value: (your Railway URL)"
echo "   → Click: Deploy"
echo "   → Done! Frontend will be live in 10 minutes"
echo ""
echo "=========================================="
echo "   APP WILL BE LIVE 24/7 - 100% FREE!"
echo "=========================================="
echo ""
echo "📱 After deployment:"
echo "   - Get customer URL from Vercel"
echo "   - Create QR code"
echo "   - Print and place on tables"
echo "   - Customers can order!"
echo ""
echo "🔑 Admin Login:"
echo "   Username: admin"
echo "   Password: admin123"
echo ""
